/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chatapp.client;

import chatapp.SharedUtil;

public class ClientMain {
    public static String TAG = "[CLIENT] :";
    public static String address = "127.0.0.1";

    public static void main(String[] args) {
        Client client = new Client(address, SharedUtil.SERVER_PORT);
        client.startClient();
    }
}
